### ISSUE TITLE
Project titles page

### ISSUE THREAD

**Issue by AndreaIdini** [Scienza/SitoAndreaIdini#5]
Nella pagina dei progetti (cf. [http://localhost:1313/staff/Andrea.Idini/projects/](http://localhost:1313/staff/Andrea.Idini/projects/) ) la visualizzazione e' un po' brutta.

![screen shot 2018-07-18 at 22 45 40](https://user-images.githubusercontent.com/6186484/42906778-55865ce4-8adc-11e8-81e0-b2a0194fc6c5.png)

1- Cambiare font per essere piu' consistenti col resto del tema (?)
2- e' possibile mettere un testo personalizzato in queste preview?
3- eventualmente ridurre heading space

---

## Stato
- [x] Stesso font usato negli articoli per il testo (#7)

- [x] Campo personalizzato per riassunto dell'articolo (#8)

- [x] Rimuovere margin-top in nome articolo (#6)

**Comment by Pandry** [comment]
1. Sì.
Vorresti usare quello all'interno degli articoli?
2. Sì: se vuoi posso ttere un capo che puoi compilare (ad esempio insieme al titolo), e posso far sì che se non è presente mette le prime parole dell'articolo
3. Anche questo è possibile, la metà dello spazio potrebbe andare bene?

**Comment by AndreaIdini** [comment]
1- Si'
2- Si'
3- perfetto

**Comment by Pandry** [comment]
- [ ] Stesso font usato negli articoli per il testo

- [ ] Campo personalizzato per riassunto dell'articolo

- [ ] Rimuovere margin-top in nome articolo

**Comment by Pandry** [comment]
#6, #7 ed #8 approvate, chiudo
